### ISSUE TITLE
Wrong icon names

### ISSUE THREAD

**Issue by TimsManter** [inzar98/optimus-manager-argos#3]
After installation icons with Intel and Nvidia logo don't show up. In result menu button is not visible.

Changing icon names in script to file names of icons fixed the issue.

**Comment by inzar98** [comment]
Its actually weird. Its works out of box for me. I dont know why. 

Can you show what did you changed for the fix ?

**Comment by TimsManter** [comment]
I assume you have these icons in your current icon pack. I use [Newaita](https://github.com/cbrnix/Newaita) so Nvidia icon and restart icon were visible in menu but not Intel because Newaita doesn't have that one.

In the installation manual you noticed copying icons is optional and it is if icon pack has these but not everyone has. In this case I had to match icons in script to file names in `~/.local/share/icons` but I think it should be the other way - file names of icons should match icon names in the script.

I made these changes to match names:

No | Line
--- | ---
47 | `nvidia_state_icon=primeindicatornvidia`
51 | `nvidia_state_icon=primeindicatorintel`
59 | `echo "Switch to INTEL \| iconName='primeindicatorintelsymbolic' bash=$activate_intel terminal=false"`
60 | `echo "Switch to NVIDIA  \| iconName='primeindicatornvidiasymbolic' bash=$activate_nvidia  terminal=false"`

Without it menu looks like this:
![image](https://user-images.githubusercontent.com/5507688/57706920-fa530f80-7666-11e9-9d7b-67bc7538c645.png)

**Comment by inzar98** [comment]
Thanks for the information!
